<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    public function run()
    {
        $countries = [
            [
                'id'         => 1,
                'name'       => 'Afghanistan',
                'short_code' => 'af',
                'dial_code'   => '+93',
                'nationality'  => 'Afghan',
            ],
            [
                'id'         => 2,
                'name'       => 'Albania',
                'short_code' => 'al',
                'dial_code'   => '+355',
                'nationality'  => 'Albanian',
            ],
            [
                'id'         => 3,
                'name'       => 'Algeria',
                'short_code' => 'dz',
                'dial_code'   => '+213',
                'nationality'  => 'Algerian',
            ],
            [
                'id'         => 4,
                'name'       => 'American Samoa',
                'short_code' => 'as',
                'dial_code'   => '+1-684',
                'nationality'  => 'American Samoan',
            ],
            [
                'id'         => 5,
                'name'       => 'Andorra',
                'short_code' => 'ad',
                'dial_code'   => '+376',
                'nationality'  => 'Andorran',
            ],
            [
                'id'         => 6,
                'name'       => 'Angola',
                'short_code' => 'ao',
                'dial_code'   => '+244',
                'nationality'  => 'Angolan',
            ],
            [
                'id'         => 7,
                'name'       => 'Anguilla',
                'short_code' => 'ai',
                'dial_code'   => '+1-264',
                'nationality'  => 'Anguillian',
            ],
            [
                'id'         => 8,
                'name'       => 'Antarctica',
                'short_code' => 'aq',
                'dial_code'   => '+672',
                'nationality'  => 'Antarctican',
            ],
            [
                'id'         => 9,
                'name'       => 'Antigua and Barbuda',
                'short_code' => 'ag',
                'dial_code'   => '+1-268',
                'nationality'  => 'Antiguan or Barbudan',
            ],
            [
                'id'         => 10,
                'name'       => 'Argentina',
                'short_code' => 'ar',
                'dial_code'   => '+54',
                'nationality'  => 'Argentine',
            ],
            [
                'id'         => 11,
                'name'       => 'Armenia',
                'short_code' => 'am',
                'dial_code'   => '+374',
                'nationality'  => 'Armenian',
            ],
            [
                'id'         => 12,
                'name'       => 'Aruba',
                'short_code' => 'aw',
                'dial_code'   => '+297',
                'nationality'  => 'Aruban',
            ],
            [
                'id'         => 13,
                'name'       => 'Australia',
                'short_code' => 'au',
                'dial_code'   => '+61',
                'nationality'  => 'Australian',
            ],
            [
                'id'         => 14,
                'name'       => 'Austria',
                'short_code' => 'at',
                'dial_code'   => '+43',
                'nationality'  => 'Austrian',
            ],
            [
                'id'         => 15,
                'name'       => 'Azerbaijan',
                'short_code' => 'az',
                'dial_code'   => '+994',
                'nationality'  => 'Azerbaijani',
            ],
            [
                'id'         => 16,
                'name'       => 'Bahamas',
                'short_code' => 'bs',
                'dial_code'   => '+1-242',
                'nationality'  => 'Bahamian',
            ],
            [
                'id'         => 17,
                'name'       => 'Bahrain',
                'short_code' => 'bh',
                'dial_code'   => '+973',
                'nationality'  => 'Bahraini',
            ],
            [
                'id'         => 18,
                'name'       => 'Bangladesh',
                'short_code' => 'bd',
                'dial_code'   => '+880',
                'nationality'  => 'Bangladeshi',
            ],
            [
                'id'         => 19,
                'name'       => 'Barbados',
                'short_code' => 'bb',
                'dial_code'   => '+1-246',
                'nationality'  => 'Barbadian',
            ],
            [
                'id'         => 20,
                'name'       => 'Belarus',
                'short_code' => 'by',
                'dial_code'   => '+375',
                'nationality'  => 'Belarusian',
            ],
            [
                'id'         => 21,
                'name'       => 'Belgium',
                'short_code' => 'be',
                'dial_code'   => '+32',
                'nationality'  => 'Belgian',
            ],
            [
                'id'         => 22,
                'name'       => 'Belize',
                'short_code' => 'bz',
                'dial_code'   => '+501',
                'nationality'  => 'Belizean',
            ],
            [
                'id'         => 23,
                'name'       => 'Benin',
                'short_code' => 'bj',
                'dial_code'   => '+229',
                'nationality'  => 'Beninese',
            ],
            [
                'id'         => 24,
                'name'       => 'Bermuda',
                'short_code' => 'bm',
                'dial_code'   => '+1-441',
                'nationality'  => 'Bermudian',
            ],
            [
                'id'         => 25,
                'name'       => 'Bhutan',
                'short_code' => 'bt',
                'dial_code'   => '+975',
                'nationality'  => 'Bhutanese',
            ],
            [
                'id'         => 26,
                'name'       => 'Bolivia',
                'short_code' => 'bo',
                'dial_code'   => '+591',
                'nationality'  => 'Bolivian',
            ],
            [
                'id'         => 27,
                'name'       => 'Bosnia and Herzegovina',
                'short_code' => 'ba',
                'dial_code'   => '+387',
                'nationality'  => 'Bosnian',
            ],
            [
                'id'         => 28,
                'name'       => 'Botswana',
                'short_code' => 'bw',
                'dial_code'   => '+267',
                'nationality'  => 'Motswana',
            ],
            [
                'id'         => 29,
                'name'       => 'Brazil',
                'short_code' => 'br',
                'dial_code'   => '+55',
                'nationality'  => 'Brazilian',
            ],
            [
                'id'         => 30,
                'name'       => 'British Indian Ocean Territory',
                'short_code' => 'io',
                'dial_code'   => '+246',
                'nationality'  => 'British Indian Ocean Territory',
            ],
            [
                'id'         => 31,
                'name'       => 'British Virgin Islands',
                'short_code' => 'vg',
                'dial_code'   => '+1-284',
                'nationality'  => 'British Virgin Islander',
            ],
            [
                'id'         => 32,
                'name'       => 'Brunei',
                'short_code' => 'bn',
                'dial_code'   => '+673',
                'nationality'  => 'Bruneian',
            ],
            [
                'id'         => 33,
                'name'       => 'Bulgaria',
                'short_code' => 'bg',
                'dial_code'   => '+359',
                'nationality'  => 'Bulgarian',
            ],
            [
                'id'         => 34,
                'name'       => 'Burkina Faso',
                'short_code' => 'bf',
                'dial_code'   => '+226',
                'nationality'  => 'Burkinabe',
            ],
            [
                'id'         => 35,
                'name'       => 'Burundi',
                'short_code' => 'bi',
                'dial_code'   => '+257',
                'nationality'  => 'Burundian',
            ],
            [
                'id'         => 36,
                'name'       => 'Cambodia',
                'short_code' => 'kh',
                'dial_code'   => '+855',
                'nationality'  => 'Khmer',
            ],
            [
                'id'         => 37,
                'name'       => 'Cameroon',
                'short_code' => 'cm',
                'dial_code'   => '+237',
                'nationality'  => 'Cameroonian',
            ],
            [
                'id'         => 38,
                'name'       => 'Canada',
                'short_code' => 'ca',
                'dial_code'   => '+1',
                'nationality'  => 'Canadian',
            ],
            [
                'id'         => 39,
                'name'       => 'Cape Verde',
                'short_code' => 'cv',
                'dial_code'   => '+238',
                'nationality'  => 'Cabo Verdean',
            ],
            [
                'id'         => 40,
                'name'       => 'Cayman Islands',
                'short_code' => 'ky',
                'dial_code'   => '+1-345',
                'nationality'  => 'Caymanian',
            ],
            [
                'id'         => 41,
                'name'       => 'Central African Republic',
                'short_code' => 'cf',
                'dial_code'   => '+236',
                'nationality'  => 'Central African',
            ],
            [
                'id'         => 42,
                'name'       => 'Chad',
                'short_code' => 'td',
                'dial_code'   => '+235',
                'nationality'  => 'Chadian',
            ],
            [
                'id'         => 43,
                'name'       => 'Chile',
                'short_code' => 'cl',
                'dial_code'   => '+56',
                'nationality'  => 'Chilean',
            ],
            [
                'id'         => 44,
                'name'       => 'China',
                'short_code' => 'cn',
                'dial_code'   => '+86',
                'nationality'  => 'Chinese',
            ],
            [
                'id'         => 45,
                'name'       => 'Christmas Island',
                'short_code' => 'cx',
                'dial_code'   => '+61',
                'nationality'  => 'Christmas Islander',
            ],
            [
                'id'         => 46,
                'name'       => 'Cocos Islands',
                'short_code' => 'cc',
                'dial_code'   => '+61',
                'nationality'  => 'Cocos Islander',
            ],
            [
                'id'         => 47,
                'name'       => 'Colombia',
                'short_code' => 'co',
                'dial_code'   => '+57',
                'nationality'  => 'Colombian',
            ],
            [
                'id'         => 48,
                'name'       => 'Comoros',
                'short_code' => 'km',
                'dial_code'   => '+269',
                'nationality'  => 'Comorian',
            ],
            [
                'id'         => 49,
                'name'       => 'Cook Islands',
                'short_code' => 'ck',
                'dial_code'   => '+682',
                'nationality'  => 'Cook Islander',
            ],
            [
                'id'         => 50,
                'name'       => 'Costa Rica',
                'short_code' => 'cr',
                'dial_code'   => '+506',
                'nationality'  => 'Costa Rican',
            ],
            [
                'id'         => 51,
                'name'       => 'Croatia',
                'short_code' => 'hr',
                'dial_code'   => '+385',
                'nationality'  => 'Croatian',
            ],
            [
                'id'         => 52,
                'name'       => 'Cuba',
                'short_code' => 'cu',
                'dial_code'   => '+53',
                'nationality'  => 'Cuban',
            ],
            [
                'id'         => 53,
                'name'       => 'Curacao',
                'short_code' => 'cw',
                'dial_code'   => '+599',
                'nationality'  => 'Curacaoan',
            ],
            [
                'id'         => 54,
                'name'       => 'Cyprus',
                'short_code' => 'cy',
                'dial_code'   => '+357',
                'nationality'  => 'Cypriot',
            ],
            [
                'id'         => 55,
                'name'       => 'Czech Republic',
                'short_code' => 'cz',
                'dial_code'   => '+420',
                'nationality'  => 'Czech',
            ],
            [
                'id'         => 56,
                'name'       => 'Democratic Republic of the Congo',
                'short_code' => 'cd',
                'dial_code'   => '+243',
                'nationality'  => 'Congolese',
            ],
            [
                'id'         => 57,
                'name'       => 'Denmark',
                'short_code' => 'dk',
                'dial_code'   => '+45',
                'nationality'  => 'Danish',
            ],
            [
                'id'         => 58,
                'name'       => 'Djibouti',
                'short_code' => 'dj',
                'dial_code'   => '+253',
                'nationality'  => 'Djiboutian',
            ],
            [
                'id'         => 59,
                'name'       => 'Dominica',
                'short_code' => 'dm',
                'dial_code'   => '+1',
                'nationality'  => 'Dominican',
            ],
            [
                'id'         => 60,
                'name'       => 'Dominican Republic',
                'short_code' => 'do',
                'dial_code'   => '+1',
                'nationality'  => 'Dominican',
            ],
            [
                'id'         => 61,
                'name'       => 'East Timor',
                'short_code' => 'tl',
                'dial_code'   => '+670',
                'nationality'  => 'East Timorese',
            ],
            [
                'id'         => 62,
                'name'       => 'Ecuador',
                'short_code' => 'ec',
                'dial_code'   => '+593',
                'nationality'  => 'Ecuadorian',
            ],
            [
                'id'         => 63,
                'name'       => 'Egypt',
                'short_code' => 'eg',
                'dial_code'   => '+20',
                'nationality'  => 'Egyptian',
            ],
            [
                'id'         => 64,
                'name'       => 'El Salvador',
                'short_code' => 'sv',
                'dial_code'   => '+503',
                'nationality'  => 'Salvadoran',
            ],
            [
                'id'         => 65,
                'name'       => 'Equatorial Guinea',
                'short_code' => 'gq',
                'dial_code'   => '+240',
                'nationality'  => 'Equatoguinean',
            ],
            [
                'id'         => 66,
                'name'       => 'Eritrea',
                'short_code' => 'er',
                'dial_code'   => '+291',
                'nationality'  => 'Eritrean',
            ],
            [
                'id'         => 67,
                'name'       => 'Estonia',
                'short_code' => 'ee',
                'dial_code'   => '+372',
                'nationality'  => 'Estonian',
            ],
            [
                'id'         => 68,
                'name'       => 'Ethiopia',
                'short_code' => 'et',
                'dial_code'   => '+251',
                'nationality'  => 'Ethiopian',
            ],
            [
                'id'         => 69,
                'name'       => 'Falkland Islands',
                'short_code' => 'fk',
                'dial_code'   => '+500',
                'nationality'  => 'Falkland Islander',
            ],
            [
                'id'         => 70,
                'name'       => 'Faroe Islands',
                'short_code' => 'fo',
                'dial_code'   => '+298',
                'nationality'  => 'Faroese',
            ],
            [
                'id'         => 71,
                'name'       => 'Fiji',
                'short_code' => 'fj',
                'dial_code'   => '+679',
                'nationality'  => 'Fijian',
            ],
            [
                'id'         => 72,
                'name'       => 'Finland',
                'short_code' => 'fi',
                'dial_code'   => '+358',
                'nationality'  => 'Finnish',
            ],
            [
                'id'         => 73,
                'name'       => 'France',
                'short_code' => 'fr',
                'dial_code'   => '+33',
                'nationality'  => 'French',
            ],
            [
                'id'         => 74,
                'name'       => 'French Polynesia',
                'short_code' => 'pf',
                'dial_code'   => '+689',
                'nationality'  => 'French Polynesian',
            ],
            [
                'id'         => 75,
                'name'       => 'Gabon',
                'short_code' => 'ga',
                'dial_code'   => '+241',
                'nationality'  => 'Gabonese',
            ],
            [
                'id'         => 76,
                'name'       => 'Gambia',
                'short_code' => 'gm',
                'dial_code'   => '+220',
                'nationality'  => 'Gambian',
            ],
            [
                'id'         => 77,
                'name'       => 'Georgia',
                'short_code' => 'ge',
                'dial_code'   => '+995',
                'nationality'  => 'Georgian',
            ],
            [
                'id'         => 78,
                'name'       => 'Germany',
                'short_code' => 'de',
                'dial_code'   => '+49',
                'nationality'  => 'German',
            ],
            [
                'id'         => 79,
                'name'       => 'Ghana',
                'short_code' => 'gh',
                'dial_code'   => '+233',
                'nationality'  => 'Ghanaian',
            ],
            [
                'id'         => 80,
                'name'       => 'Gibraltar',
                'short_code' => 'gi',
                'dial_code'   => '+350',
                'nationality'  => 'Gibraltarian',
            ],
            [
                'id'         => 81,
                'name'       => 'Greece',
                'short_code' => 'gr',
                'dial_code'   => '+30',
                'nationality'  => 'Greek',
            ],
            [
                'id'         => 82,
                'name'       => 'Greenland',
                'short_code' => 'gl',
                'dial_code'   => '+299',
                'nationality'  => 'Greenlander',
            ],
            [
                'id'         => 83,
                'name'       => 'Grenada',
                'short_code' => 'gd',
                'dial_code'   => '+1',
                'nationality'  => 'Grenadian',
            ],
            [
                'id'         => 84,
                'name'       => 'Guam',
                'short_code' => 'gu',
                'dial_code'   => '+1',
                'nationality'  => 'Guamanian',
            ],
            [
                'id'         => 85,
                'name'       => 'Guatemala',
                'short_code' => 'gt',
                'dial_code'   => '+502',
                'nationality'  => 'Guatemalan',
            ],
            [
                'id'         => 86,
                'name'       => 'Guernsey',
                'short_code' => 'gg',
                'dial_code'   => '+44',
                'nationality'  => 'Guernsey',
            ],
            [
                'id'         => 87,
                'name'       => 'Guinea',
                'short_code' => 'gn',
                'dial_code'   => '+224',
                'nationality'  => 'Guinean',
            ],
            [
                'id'         => 88,
                'name'       => 'Guinea-Bissau',
                'short_code' => 'gw',
                'dial_code'   => '+245',
                'nationality'  => 'Bissau-Guinean',
            ],
            [
                'id'         => 89,
                'name'       => 'Guyana',
                'short_code' => 'gy',
                'dial_code'   => '+592',
                'nationality'  => 'Guyanese',
            ],
            [
                'id'         => 90,
                'name'       => 'Haiti',
                'short_code' => 'ht',
                'dial_code'   => '+509',
                'nationality'  => 'Haitian',
            ],
            [
                'id'         => 91,
                'name'       => 'Honduras',
                'short_code' => 'hn',
                'dial_code'   => '+504',
                'nationality'  => 'Honduran',
            ],
            [
                'id'         => 92,
                'name'       => 'Hong Kong',
                'short_code' => 'hk',
                'dial_code'   => '+852',
                'nationality'  => 'Hong Konger',
            ],
            [
                'id'         => 93,
                'name'       => 'Hungary',
                'short_code' => 'hu',
                'dial_code'   => '+36',
                'nationality'  => 'Hungarian',
            ],
            [
                'id'         => 94,
                'name'       => 'Iceland',
                'short_code' => 'is',
                'dial_code'   => '+354',
                'nationality'  => 'Icelander',
            ],
            [
                'id'         => 95,
                'name'       => 'India',
                'short_code' => 'in',
                'dial_code'   => '+91',
                'nationality'  => 'Indian',
            ],
            [
                'id'         => 96,
                'name'       => 'Indonesia',
                'short_code' => 'id',
                'dial_code'   => '+62',
                'nationality'  => 'Indonesian',
            ],
            [
                'id'         => 97,
                'name'       => 'Iran',
                'short_code' => 'ir',
                'dial_code'   => '+98',
                'nationality'  => 'Iranian',
            ],
            [
                'id'         => 98,
                'name'       => 'Iraq',
                'short_code' => 'iq',
                'dial_code'   => '+964',
                'nationality'  => 'Iraqi',
            ],
            [
                'id'         => 99,
                'name'       => 'Ireland',
                'short_code' => 'ie',
                'dial_code'   => '+353',
                'nationality'  => 'Irish',
            ],
            [
                'id'         => 100,
                'name'       => 'Isle of Man',
                'short_code' => 'im',
                'dial_code'   => '+44',
                'nationality'  => 'Manx',
            ],
            [
                'id'         => 101,
                'name'       => 'Israel',
                'short_code' => 'il',
                'dial_code'   => '+972',
                'nationality'  => 'Israeli',
            ],
            [
                'id'         => 102,
                'name'       => 'Italy',
                'short_code' => 'it',
                'dial_code'   => '+39',
                'nationality'  => 'Italian',
            ],
            [
                'id'         => 103,
                'name'       => 'Ivory Coast',
                'short_code' => 'ci',
                'dial_code'   => '+225',
                'nationality'  => 'Ivorian',
            ],
            [
                'id'         => 104,
                'name'       => 'Jamaica',
                'short_code' => 'jm',
                'dial_code'   => '+1-876',
                'nationality'  => 'Jamaican',
            ],
            [
                'id'         => 105,
                'name'       => 'Japan',
                'short_code' => 'jp',
                'dial_code'   => '+81',
                'nationality'  => 'Japanese',
            ],
            [
                'id'         => 106,
                'name'       => 'Jersey',
                'short_code' => 'je',
                'dial_code'   => '+44',
                'nationality'  => 'Jerseyman',
            ],
            [
                'id'         => 107,
                'name'       => 'Jordan',
                'short_code' => 'jo',
                'dial_code'   => '+962',
                'nationality'  => 'Jordanian',
            ],
            [
                'id'         => 108,
                'name'       => 'Kazakhstan',
                'short_code' => 'kz',
                'dial_code'   => '+7',
                'nationality'  => 'Kazakhstani',
            ],
            [
                'id'         => 109,
                'name'       => 'Kenya',
                'short_code' => 'ke',
                'dial_code'   => '+254',
                'nationality'  => 'Kenyan',
            ],
            [
                'id'         => 110,
                'name'       => 'Kiribati',
                'short_code' => 'ki',
                'dial_code'   => '+686',
                'nationality'  => 'I-Kiribati',
            ],
            [
                'id'         => 111,
                'name'       => 'Kosovo',
                'short_code' => 'xk',
                'dial_code'   => '+383',
                'nationality'  => 'Kosovar',
            ],
            [
                'id'         => 112,
                'name'       => 'Kuwait',
                'short_code' => 'kw',
                'dial_code'   => '+965',
                'nationality'  => 'Kuwaiti',
            ],
            [
                'id'         => 113,
                'name'       => 'Kyrgyzstan',
                'short_code' => 'kg',
                'dial_code'   => '+996',
                'nationality'  => 'Kyrgyzstani',
            ],
            [
                'id'         => 114,
                'name'       => 'Laos',
                'short_code' => 'la',
                'dial_code'   => '+856',
                'nationality'  => 'Laotian',
            ],
            [
                'id'         => 115,
                'name'       => 'Latvia',
                'short_code' => 'lv',
                'dial_code'   => '+371',
                'nationality'  => 'Latvian',
            ],
            [
                'id'         => 116,
                'name'       => 'Lebanon',
                'short_code' => 'lb',
                'dial_code'   => '+961',
                'nationality'  => 'Lebanese',
            ],
            [
                'id'         => 117,
                'name'       => 'Lesotho',
                'short_code' => 'ls',
                'dial_code'   => '+266',
                'nationality'  => 'Basotho',
            ],
            [
                'id'         => 118,
                'name'       => 'Liberia',
                'short_code' => 'lr',
                'dial_code'   => '+231',
                'nationality'  => 'Liberian',
            ],
            [
                'id'         => 119,
                'name'       => 'Libya',
                'short_code' => 'ly',
                'dial_code'   => '+218',
                'nationality'  => 'Libyan',
            ],
            [
                'id'         => 120,
                'name'       => 'Liechtenstein',
                'short_code' => 'li',
                'dial_code'   => '+423',
                'nationality'  => 'Liechtensteiner',
            ],
            [
                'id'         => 121,
                'name'       => 'Lithuania',
                'short_code' => 'lt',
                'dial_code'   => '+370',
                'nationality'  => 'Lithuanian',
            ],
            [
                'id'         => 122,
                'name'       => 'Luxembourg',
                'short_code' => 'lu',
                'dial_code'   => '+352',
                'nationality'  => 'Luxembourger',
            ],
            [
                'id'         => 123,
                'name'       => 'Macau',
                'short_code' => 'mo',
                'dial_code'   => '+853',
                'nationality'  => 'Macanese',
            ],
            [
                'id'         => 124,
                'name'       => 'Macedonia',
                'short_code' => 'mk',
                'dial_code'   => '+389',
                'nationality'  => 'Macedonian',
            ],
            [
                'id'         => 125,
                'name'       => 'Madagascar',
                'short_code' => 'mg',
                'dial_code'   => '+261',
                'nationality'  => 'Malagasy',
            ],
            [
                'id'         => 126,
                'name'       => 'Malawi',
                'short_code' => 'mw',
                'dial_code'   => '+265',
                'nationality'  => 'Malawian',
            ],
            [
                'id'         => 127,
                'name'       => 'Malaysia',
                'short_code' => 'my',
                'dial_code'   => '+60',
                'nationality'  => 'Malaysian',
            ],
            [
                'id'         => 128,
                'name'       => 'Maldives',
                'short_code' => 'mv',
                'dial_code'   => '+960',
                'nationality'  => 'Maldivian',
            ],
            [
                'id'         => 129,
                'name'       => 'Mali',
                'short_code' => 'ml',
                'dial_code'   => '+223',
                'nationality'  => 'Malian',
            ],
            [
                'id'         => 130,
                'name'       => 'Malta',
                'short_code' => 'mt',
                'dial_code'   => '+356',
                'nationality'  => 'Maltese',
            ],
            [
                'id'         => 131,
                'name'       => 'Marshall Islands',
                'short_code' => 'mh',
                'dial_code'   => '+692',
                'nationality'  => 'Marshallese',
            ],
            [
                'id'         => 132,
                'name'       => 'Mauritania',
                'short_code' => 'mr',
                'dial_code'   => '+222',
                'nationality'  => 'Mauritanian',
            ],
            [
                'id'         => 133,
                'name'       => 'Mauritius',
                'short_code' => 'mu',
                'dial_code'   => '+230',
                'nationality'  => 'Mauritian',
            ],
            [
                'id'         => 134,
                'name'       => 'Mayotte',
                'short_code' => 'yt',
                'dial_code'   => '+262',
                'nationality'  => 'Mahoran',
            ],
            [
                'id'         => 135,
                'name'       => 'Mexico',
                'short_code' => 'mx',
                'dial_code'   => '+52',
                'nationality'  => 'Mexican',
            ],
            [
                'id'         => 136,
                'name'       => 'Micronesia',
                'short_code' => 'fm',
                'dial_code'   => '+691',
                'nationality'  => 'Micronesian',
            ],
            [
                'id'         => 137,
                'name'       => 'Moldova',
                'short_code' => 'md',
                'dial_code'   => '+373',
                'nationality'  => 'Moldovan',
            ],
            [
                'id'         => 138,
                'name'       => 'Monaco',
                'short_code' => 'mc',
                'dial_code'   => '+377',
                'nationality'  => 'Monegasque',
            ],
            [
                'id'         => 139,
                'name'       => 'Mongolia',
                'short_code' => 'mn',
                'dial_code'   => '+976',
                'nationality'  => 'Mongolian',
            ],
            [
                'id'         => 140,
                'name'       => 'Montenegro',
                'short_code' => 'me',
                'dial_code'   => '+382',
                'nationality'  => 'Montenegrin',
            ],
            [
                'id'         => 141,
                'name'       => 'Montserrat',
                'short_code' => 'ms',
                'dial_code'   => '+1 664',
                'nationality'  => 'Montserratian',
            ],
            [
                'id'         => 142,
                'name'       => 'Morocco',
                'short_code' => 'ma',
                'dial_code'   => '+212',
                'nationality'  => 'Moroccan',
            ],
            [
                'id'         => 143,
                'name'       => 'Mozambique',
                'short_code' => 'mz',
                'dial_code'   => '+258',
                'nationality'  => 'Mozambican',
            ],
            [
                'id'         => 144,
                'name'       => 'Myanmar',
                'short_code' => 'mm',
                'dial_code'   => '+95',
                'nationality'  => 'Burmese',
            ],
            [
                'id'         => 145,
                'name'       => 'Namibia',
                'short_code' => 'na',
                'dial_code'   => '+264',
                'nationality'  => 'Namibian',
            ],
            [
                'id'         => 146,
                'name'       => 'Nauru',
                'short_code' => 'nr',
                'dial_code'   => '+674',
                'nationality'  => 'Nauruan',
            ],
            [
                'id'         => 147,
                'name'       => 'Nepal',
                'short_code' => 'np',
                'dial_code'   => '+977',
                'nationality'  => 'Nepali',
            ],
            [
                'id'         => 148,
                'name'       => 'Netherlands',
                'short_code' => 'nl',
                'dial_code'   => '+31',
                'nationality'  => 'Dutch',
            ],
            [
                'id'         => 149,
                'name'       => 'Netherlands Antilles',
                'short_code' => 'an',
                'dial_code'   => '+599',
                'nationality'  => 'Dutch Antillean',
            ],
            [
                'id'         => 150,
                'name'       => 'New Caledonia',
                'short_code' => 'nc',
                'dial_code'   => '+687',
                'nationality'  => 'New Caledonian',
            ],
            [
                'id'         => 151,
                'name'       => 'New Zealand',
                'short_code' => 'nz',
                'dial_code'   => '+64',
                'nationality'  => 'New Zealander',
            ],
            [
                'id'         => 152,
                'name'       => 'Nicaragua',
                'short_code' => 'ni',
                'dial_code'   => '+505',
                'nationality'  => 'Nicaraguan',
            ],
            [
                'id'         => 153,
                'name'       => 'Niger',
                'short_code' => 'ne',
                'dial_code'   => '+227',
                'nationality'  => 'Nigerien',
            ],
            [
                'id'         => 154,
                'name'       => 'Nigeria',
                'short_code' => 'ng',
                'dial_code'   => '+234',
                'nationality'  => 'Nigerian',
            ],
            [
                'id'         => 155,
                'name'       => 'Niue',
                'short_code' => 'nu',
                'dial_code'   => '+683',
                'nationality'  => 'Niuean',
            ],
            [
                'id'         => 156,
                'name'       => 'North Korea',
                'short_code' => 'kp',
                'dial_code'   => '+850',
                'nationality'  => 'North Korean',
            ],
            [
                'id'         => 157,
                'name'       => 'Northern Mariana Islands',
                'short_code' => 'mp',
                'dial_code'   => '+1 670',
                'nationality'  => 'Northern Mariana Islander',
            ],
            [
                'id'         => 158,
                'name'       => 'Norway',
                'short_code' => 'no',
                'dial_code'   => '+47',
                'nationality'  => 'Norwegian',
            ],
            [
                'id'         => 159,
                'name'       => 'Oman',
                'short_code' => 'om',
                'dial_code'   => '+968',
                'nationality'  => 'Omani',
            ],
            [
                'id'         => 160,
                'name'       => 'Pakistan',
                'short_code' => 'pk',
                'dial_code'   => '+92',
                'nationality'  => 'Pakistani',
            ],
            [
                'id'         => 161,
                'name'       => 'Palau',
                'short_code' => 'pw',
                'dial_code'   => '+680',
                'nationality'  => 'Palauan',
            ],
            [
                'id'         => 162,
                'name'       => 'Palestine',
                'short_code' => 'ps',
                'dial_code'   => '+970',
                'nationality'  => 'Palestinian',
            ],
            [
                'id'         => 163,
                'name'       => 'Panama',
                'short_code' => 'pa',
                'dial_code'   => '+507',
                'nationality'  => 'Panamanian',
            ],
            [
                'id'         => 164,
                'name'       => 'Papua New Guinea',
                'short_code' => 'pg',
                'dial_code'   => '+675',
                'nationality'  => 'Papua New Guinean',
            ],
            [
                'id'         => 165,
                'name'       => 'Paraguay',
                'short_code' => 'py',
                'dial_code'   => '+595',
                'nationality'  => 'Paraguayan',
            ],
            [
                'id'         => 166,
                'name'       => 'Peru',
                'short_code' => 'pe',
                'dial_code'   => '+51',
                'nationality'  => 'Peruvian',
            ],
            [
                'id'         => 167,
                'name'       => 'Philippines',
                'short_code' => 'ph',
                'dial_code'   => '+63',
                'nationality'  => 'Filipino',
            ],
            [
                'id'         => 168,
                'name'       => 'Pitcairn',
                'short_code' => 'pn',
                'dial_code'   => '+64',
                'nationality'  => 'Pitcairn Islander',
            ],
            [
                'id'         => 169,
                'name'       => 'Poland',
                'short_code' => 'pl',
                'dial_code'   => '+48',
                'nationality'  => 'Polish',
            ],
            [
                'id'         => 170,
                'name'       => 'Portugal',
                'short_code' => 'pt',
                'dial_code'   => '+351',
                'nationality'  => 'Portuguese',
            ],
            [
                'id'         => 171,
                'name'       => 'Puerto Rico',
                'short_code' => 'pr',
                'dial_code'   => '+1 787',
                'nationality'  => 'Puerto Rican',
            ],
            [
                'id'         => 172,
                'name'       => 'Qatar',
                'short_code' => 'qa',
                'dial_code'   => '+974',
                'nationality'  => 'Qatari',
            ],
            [
                'id'         => 173,
                'name'       => 'Republic of the Congo',
                'short_code' => 'cg',
                'dial_code'   => '+242',
                'nationality'  => 'Congolese',
            ],
            [
                'id'         => 174,
                'name'       => 'Reunion',
                'short_code' => 're',
                'dial_code'   => '+262',
                'nationality'  => 'Reunionese',
            ],
            [
                'id'         => 175,
                'name'       => 'Romania',
                'short_code' => 'ro',
                'dial_code'   => '+40',
                'nationality'  => 'Romanian',
            ],
            [
                'id'         => 176,
                'name'       => 'Russia',
                'short_code' => 'ru',
                'dial_code'   => '+7',
                'nationality'  => 'Russian',
            ],
            [
                'id'         => 177,
                'name'       => 'Rwanda',
                'short_code' => 'rw',
                'dial_code'   => '+250',
                'nationality'  => 'Rwandese',
            ],
            [
                'id'         => 178,
                'name'       => 'Saint Barthelemy',
                'short_code' => 'bl',
                'dial_code'   => '+590',
                'nationality'  => 'Barthudian',
            ],
            [
                'id'         => 179,
                'name'       => 'Saint Helena',
                'short_code' => 'sh',
                'dial_code'   => '+290',
                'nationality'  => 'Saint Helenian',
            ],
            [
                'id'         => 180,
                'name'       => 'Saint Kitts and Nevis',
                'short_code' => 'kn',
                'dial_code'   => '+1 869',
                'nationality'  => 'Kittitian and Nevisian',
            ],
            [
                'id'         => 181,
                'name'       => 'Saint Lucia',
                'short_code' => 'lc',
                'dial_code'   => '+1 758',
                'nationality'  => 'Saint Lucian',
            ],
            [
                'id'         => 182,
                'name'       => 'Saint Martin',
                'short_code' => 'mf',
                'dial_code'   => '+590',
                'nationality'  => 'Saint Martiner',
            ],
            [
                'id'         => 183,
                'name'       => 'Saint Pierre and Miquelon',
                'short_code' => 'pm',
                'dial_code'   => '+508',
                'nationality'  => 'Saint Pierre and Miquelonese',
            ],
            [
                'id'         => 184,
                'name'       => 'Saint Vincent and the Grenadines',
                'short_code' => 'vc',
                'dial_code'   => '+1 784',
                'nationality'  => 'Saint Vincentian',
            ],
            [
                'id'         => 185,
                'name'       => 'Samoa',
                'short_code' => 'ws',
                'dial_code'   => '+685',
                'nationality'  => 'Samoan',
            ],
            [
                'id'         => 186,
                'name'       => 'San Marino',
                'short_code' => 'sm',
                'dial_code'   => '+378',
                'nationality'  => 'San Marinese',
            ],
            [
                'id'         => 187,
                'name'       => 'Sao Tome and Principe',
                'short_code' => 'st',
                'dial_code'   => '+239',
                'nationality'  => 'Sao Tomean',
            ],
            [
                'id'         => 188,
                'name'       => 'Saudi Arabia',
                'short_code' => 'sa',
                'dial_code'   => '+966',
                'nationality'  => 'Saudi Arabian',
            ],
            [
                'id'         => 189,
                'name'       => 'Senegal',
                'short_code' => 'sn',
                'dial_code'   => '+221',
                'nationality'  => 'Senegalese',
            ],
            [
                'id'         => 190,
                'name'       => 'Serbia',
                'short_code' => 'rs',
                'dial_code'   => '+381',
                'nationality'  => 'Serbian',
            ],
            [
                'id'         => 191,
                'name'       => 'Seychelles',
                'short_code' => 'sc',
                'dial_code'   => '+248',
                'nationality'  => 'Seychellois',
            ],
            [
                'id'         => 192,
                'name'       => 'Sierra Leone',
                'short_code' => 'sl',
                'dial_code'   => '+232',
                'nationality'  => 'Sierra Leonean',
            ],
            [
                'id'         => 193,
                'name'       => 'Singapore',
                'short_code' => 'sg',
                'dial_code'   => '+65',
                'nationality'  => 'Singaporean',
            ],
            [
                'id'         => 194,
                'name'       => 'Sint Maarten',
                'short_code' => 'sx',
                'dial_code'   => '+1 721',
                'nationality'  => 'Sint Maartener',
            ],
            [
                'id'         => 195,
                'name'       => 'Slovakia',
                'short_code' => 'sk',
                'dial_code'   => '+421',
                'nationality'  => 'Slovak',
            ],
            [
                'id'         => 196,
                'name'       => 'Slovenia',
                'short_code' => 'si',
                'dial_code'   => '+386',
                'nationality'  => 'Slovenian',
            ],
            [
                'id'         => 197,
                'name'       => 'Solomon Islands',
                'short_code' => 'sb',
                'dial_code'   => '+677',
                'nationality'  => 'Solomon Islander',
            ],
            [
                'id'         => 198,
                'name'       => 'Somalia',
                'short_code' => 'so',
                'dial_code'   => '+252',
                'nationality'  => 'Somali',
            ],
            [
                'id'         => 199,
                'name'       => 'South Africa',
                'short_code' => 'za',
                'dial_code'   => '+27',
                'nationality'  => 'South African',
            ],
            [
                'id'         => 200,
                'name'       => 'South Korea',
                'short_code' => 'kr',
                'dial_code'   => '+82',
                'nationality'  => 'South Korean',
            ],
            [
                'id'         => 201,
                'name'       => 'South Sudan',
                'short_code' => 'ss',
                'dial_code'   => '+211',
                'nationality'  => 'South Sudanese',
            ],
            [
                'id'         => 202,
                'name'       => 'Spain',
                'short_code' => 'es',
                'dial_code'   => '+34',
                'nationality'  => 'Spanish',
            ],
            [
                'id'         => 203,
                'name'       => 'Sri Lanka',
                'short_code' => 'lk',
                'dial_code'   => '+94',
                'nationality'  => 'Sri Lankan',
            ],
            [
                'id'         => 204,
                'name'       => 'Sudan',
                'short_code' => 'sd',
                'dial_code'   => '+249',
                'nationality'  => 'Sudanese',
            ],
            [
                'id'         => 205,
                'name'       => 'Suriname',
                'short_code' => 'sr',
                'dial_code'   => '+597',
                'nationality'  => 'Surinamese',
            ],
            [
                'id'         => 206,
                'name'       => 'Svalbard and Jan Mayen',
                'short_code' => 'sj',
                'dial_code'   => '+47',
                'nationality'  => 'Norwegian',
            ],
            [
                'id'         => 207,
                'name'       => 'Swaziland',
                'short_code' => 'sz',
                'dial_code'   => '+268',
                'nationality'  => 'Swazi',
            ],
            [
                'id'         => 208,
                'name'       => 'Sweden',
                'short_code' => 'se',
                'dial_code'   => '+46',
                'nationality'  => 'Swedish',
            ],
            [
                'id'         => 209,
                'name'       => 'Switzerland',
                'short_code' => 'ch',
                'dial_code'   => '+41',
                'nationality'  => 'Swiss',
            ],
            [
                'id'         => 210,
                'name'       => 'Syria',
                'short_code' => 'sy',
                'dial_code'   => '+963',
                'nationality'  => 'Syrian',
            ],

            [
                'id'         => 211,
                'name'       => 'Taiwan',
                'short_code' => 'tw',
                'dial_code'   => '+886',
                'nationality'  => 'Taiwanese',
            ],
            [
                'id'         => 212,
                'name'       => 'Tajikistan',
                'short_code' => 'tj',
                'dial_code'   => '+992',
                'nationality'  => 'Tajik',
            ],
            [
                'id'         => 213,
                'name'       => 'Tanzania',
                'short_code' => 'tz',
                'dial_code'   => '+255',
                'nationality'  => 'Tanzanian',
            ],
            [
                'id'         => 214,
                'name'       => 'Thailand',
                'short_code' => 'th',
                'dial_code'   => '+66',
                'nationality'  => 'Thai',
            ],
            [
                'id'         => 215,
                'name'       => 'Togo',
                'short_code' => 'tg',
                'dial_code'   => '+228',
                'nationality'  => 'Togolese',
            ],
            [
                'id'         => 216,
                'name'       => 'Tokelau',
                'short_code' => 'tk',
                'dial_code'   => '+690',
                'nationality'  => 'Tokelauan',
            ],
            [
                'id'         => 217,
                'name'       => 'Tonga',
                'short_code' => 'to',
                'dial_code'   => '+676',
                'nationality'  => 'Tongan',
            ],
            [
                'id'         => 218,
                'name'       => 'Trinidad and Tobago',
                'short_code' => 'tt',
                'dial_code'   => '+1',
                'nationality'  => 'Trinidadian',
            ],
            [
                'id'         => 219,
                'name'       => 'Tunisia',
                'short_code' => 'tn',
                'dial_code'   => '+216',
                'nationality'  => 'Tunisian',
            ],
            [
                'id'         => 220,
                'name'       => 'Turkey',
                'short_code' => 'tr',
                'dial_code'   => '+90',
                'nationality'  => 'Turkish',
            ],
            [
                'id'         => 221,
                'name'       => 'Turkmenistan',
                'short_code' => 'tm',
                'dial_code'   => '+993',
                'nationality'  => 'Turkmen',
            ],
            [
                'id'         => 222,
                'name'       => 'Turks and Caicos Islands',
                'short_code' => 'tc',
                'dial_code'   => '+1',
                'nationality'  => 'Turks Islander',
            ],
            [
                'id'         => 223,
                'name'       => 'Tuvalu',
                'short_code' => 'tv',
                'dial_code'   => '+688',
                'nationality'  => 'Tuvaluan',
            ],
            [
                'id'         => 224,
                'name'       => 'U.S. Virgin Islands',
                'short_code' => 'vi',
                'dial_code'   => '+1',
                'nationality'  => 'U.S. Virgin Islander',
            ],
            [
                'id'         => 225,
                'name'       => 'Uganda',
                'short_code' => 'ug',
                'dial_code'   => '+256',
                'nationality'  => 'Ugandan',
            ],
            [
                'id'         => 226,
                'name'       => 'Ukraine',
                'short_code' => 'ua',
                'dial_code'   => '+380',
                'nationality'  => 'Ukrainian',
            ],
            [
                'id'         => 227,
                'name'       => 'United Arab Emirates',
                'short_code' => 'ae',
                'dial_code'   => '+971',
                'nationality'  => 'Emirati',
            ],
            [
                'id'         => 228,
                'name'       => 'United Kingdom',
                'short_code' => 'gb',
                'dial_code'   => '+44',
                'nationality'  => 'British',
            ],
            [
                'id'         => 229,
                'name'       => 'United States',
                'short_code' => 'us',
                'dial_code'   => '+1',
                'nationality'  => 'American',
            ],
            [
                'id'         => 230,
                'name'       => 'Uruguay',
                'short_code' => 'uy',
                'dial_code'   => '+598',
                'nationality'  => 'Uruguayan',
            ],
            [
                'id'         => 231,
                'name'       => 'Uzbekistan',
                'short_code' => 'uz',
                'dial_code'   => '+998',
                'nationality'  => 'Uzbek',
            ],
            [
                'id'         => 232,
                'name'       => 'Vanuatu',
                'short_code' => 'vu',
                'dial_code'   => '+678',
                'nationality'  => 'Vanuatuan',
            ],
            [
                'id'         => 233,
                'name'       => 'Vatican',
                'short_code' => 'va',
                'dial_code'   => '+39',
                'nationality'  => 'Vatican',
            ],
            [
                'id'         => 234,
                'name'       => 'Venezuela',
                'short_code' => 've',
                'dial_code'   => '+58',
                'nationality'  => 'Venezuelan',
            ],
            [
                'id'         => 235,
                'name'       => 'Vietnam',
                'short_code' => 'vn',
                'dial_code'   => '+84',
                'nationality'  => 'Vietnamese',
            ],
            [
                'id'         => 236,
                'name'       => 'Wallis and Futuna',
                'short_code' => 'wf',
                'dial_code'   => '+681',
                'nationality'  => 'Wallisian and Futunese',
            ],
            [
                'id'         => 237,
                'name'       => 'Western Sahara',
                'short_code' => 'eh',
                'dial_code'   => '+212',
                'nationality'  => 'Western Saharan',
            ],
            [
                'id'         => 238,
                'name'       => 'Yemen',
                'short_code' => 'ye',
                'dial_code'   => '+967',
                'nationality'  => 'Yemeni',
            ],
            [
                'id'         => 239,
                'name'       => 'Zambia',
                'short_code' => 'zm',
                'dial_code'   => '+260',
                'nationality'  => 'Zambian',
            ],
            [
                'id'         => 240,
                'name'       => 'Zimbabwe',
                'short_code' => 'zw',
                'dial_code'   => '+263',
                'nationality'  => 'Zimbabwean',
            ],
        ];

        Country::insert($countries);
    }
}
